export const ROUTES = {
  home: '/',
  products: '/product',
  productDetail: (type, slug) => `/product/${type}/${slug}`,
  categories: '/categories',
  categoryDetail: (slug) => `/categories/${slug}`,
  login: '/login',
  register: '/register',
  account: '/account',
  orders: '/account/orders',
  favorites: '/account/favorites',
  cart: '/winkelmand',
  checkout: '/afrekenen',
  checkoutResult: '/afrekenen/result',
  search: '/search',
  about: '/about',
  contact: '/contact-us',
};
